# clipit
# Autogenerated from man page /usr/share/man/man1/clipit.1.gz
complete -c clipit -s '?' -l help -d 'Show help options'
complete -c clipit -s d -l daemon -d 'Run as daemon'
complete -c clipit -s n -l no-icon -d 'Do not use status icon'
complete -c clipit -s c -l clipboard -d 'Print clipboard contents'
complete -c clipit -s p -l primary -d 'Print primary contents'

