# unclutter
# Autogenerated from man page /usr/share/man/man1/unclutter.1.gz
complete -c unclutter -l timeout -d 'Specifies the number of seconds after which the cursor should be hidden if it…'
complete -c unclutter -l jitter -d 'Ignore cursor movements if the cursor hasn\'t moved sufficiently far'
complete -c unclutter -l exclude-root -d 'Don\'t hide the mouse cursor if it is idling over the root window and not an a…'
complete -c unclutter -l ignore-scrolling -d 'Ignore mouse scroll events (buttons 4 and 5) so that scrolling doesn\'t unhide…'
complete -c unclutter -l fork -s b -d 'Fork unclutter to the background'
complete -c unclutter -l help -s h -d 'Display the usage and exit'
complete -c unclutter -l version -s v -d 'Display the version and exit'
complete -c unclutter -l display -s d
complete -c unclutter -l idle
complete -c unclutter -l keystroke
complete -c unclutter -l grab
complete -c unclutter -l noevents
complete -c unclutter -l reset
complete -c unclutter -l root
complete -c unclutter -l onescreen
complete -c unclutter -l not

